const axios = require('axios');

const formatText =
  'Analyze the following customer-agent conversation and answer the questions. Ensure your response follows **ONLY** this strict JSON format (no extra text): ```json {   secure_info:Yes/No,   communication_clarity: Poor/Average/Good,   alternative_solutions: Poor/Average/Good,   call_flow: Poor/Average/Good,   agent_demeanor: Poor/Average/Good, follow_up: Yes/No} Ensure your response follows the EXACT same criteria every time. Use the same classification logic. If uncertain, choose the closest prior response.';
const testCases = [
  {
    type: 'HealthCare',
    text: 'Patient: Hi, I need help refilling my prescription for Metformin. My pharmacy said my insurance did not cover it. Agent (Sarah): Hello! Thank you for reaching out to Healthcare Support. I’m Sarah. I can certainly check that for you. Can you please provide your prescription ID or the name of your prescribing doctor? Patient: Sure, my prescription ID is RX123456. Agent (Sarah): Thank you! Let me pull up your details... I see that your prescription for Metformin was last filled on January 15th, and you are due for a refill. However, I also notice that your insurance provider, HealthPlus, updated its coverage policy this month. Patient: Oh, so that’s why the pharmacy said it’s not covered. What are my options? Agent (Sarah): There are a few options: 1️⃣ You can check with your doctor to see if an alternative medication is covered. 2️⃣ You may qualify for a manufacturer’s discount or a patient assistance program 3️⃣ You can choose to pay out of pocket, and I can provide pricing information. Patient: I’d like to check for discounts first. Agent (Sarah): Certainly! I see that the manufacturer offers a discount card that can reduce your cost by up to 50%. Would you like me to send you the details via email or text? Patient: Email would be great. Agent (Sarah): Done! I’ve sent the details to your registered email. Also, would you like me to connect you with a healthcare specialist to discuss alternative medications? Patient: Yes, that would be helpful. Agent (Sarah): Great! I’ve scheduled a callback from one of our specialists within the next 24 hours. You’ll receive a confirmation shortly. Patient: Thank you so much, Sarah. You’ve been really helpful! Agent (Sarah): My pleasure! If you need anything else, don’t hesitate to reach out. Have a great day!',
    prompt: `Analyze the following healthcare customer-agent conversation and answer the questions:{conversation} 1) Did the agent handle sensitive patient information securely and confidentially? (Yes/No)  2) How clear and effective was the agent's communication? (Poor, Average, Good)  3) Did the agent provide alternative solutions effectively? (Poor, Average, Good)  4) How well did the agent manage the call flow? (Poor, Average, Good)  5) How professional and empathetic was the agent's demeanor? (Poor, Average, Good)   6) Did the agent offer to follow up on unresolved issues? (Yes/No)   Provide answers in JSON format. ${formatText}`,
  },
  {
    type: 'HealthCare',
    text: 'Patient: Hi, I need help refilling my prescription for Metformin. My pharmacy said my insurance did not cover it. Agent (John): Yeah, well, if they said it’s not covered, then there’s not much we can do. Patient: But I need this medication! Isn’t there another way? Agent (John): I mean, you could pay for it yourself. That’s about it. Patient: Can you at least check if there are any discounts or alternative options? Agent (John): Ugh, fine. Let me check... (pause) Nope, looks like your insurance doesn’t cover it anymore. Patient: What about speaking to my doctor for alternatives? Agent (John): You can do that on your own time. We don’t handle that here. Patient: Can I get a callback from a specialist? Agent (John): No, we don’t schedule callbacks. You’ll have to figure this out yourself. Patient: This is really frustrating. Agent (John): Well, I can’t change your insurance policy, so not much I can do. Patient: I guess I’ll have to call someone else for help. Agent (John): Sure, do whatever you want. Bye.',
    prompt: `Analyze the following healthcare customer-agent conversation and answer the questions:{conversation} 1) Did the agent handle sensitive patient information securely and confidentially? (Yes/No) 2) How clear and effective was the agent's communication? (Poor, Average, Good) 3) Did the agent provide alternative solutions effectively? (Poor, Average, Good) 4) How well did the agent manage the call flow? (Poor, Average, Good) 5) How professional and empathetic was the agent's demeanor? (Poor, Average, Good) 6) Did the agent offer to follow up on unresolved issues? (Yes/No). ${formatText}`,
  },
  {
    type: 'BFSI',
    text: 'Customer: Hi, I just noticed some unauthorized transactions on my credit card, and I need to report fraud. Agent (David): Hello! Thank you for contacting SecureBank Support. My name is David, and I’ll assist you today. I’m sorry to hear about the unauthorized transactions. I’ll need to verify your identity first. Can you please confirm your last transaction and the last four digits of your card? Customer: Sure! My last valid transaction was $45 at Grocery Mart, and my card ends in 5678. Agent (David): Thank you for verifying. I see that there are three transactions flagged as suspicious: 1️⃣ $150 at TechZone 2️⃣ $200 at OnlineSportsGear.com 3️⃣ $50 at FastPay Wallet Transfer Do these transactions look unfamiliar to you? Customer: No, I didn’t make any of those. Agent (David): Understood. I will initiate a fraud investigation immediately. I’ve temporarily blocked your card to prevent further unauthorized transactions.Customer: Oh, okay. What happens next? Agent (David): Here’s what will happen: ✅ A dispute report will be filed on your behalf. ✅ We’ll investigate the transactions within 5 business days. ✅ If the charges are confirmed as fraudulent, you’ll receive a refund. In the meantime, I can issue you a replacement card. Would you like me to proceed with that? Customer: Yes, please. Agent (David): Done! Your new card will be delivered within 3-5 business days. You’ll also receive a tracking email. Customer: Thank you! Do I need to do anything else? Agent (David): Just keep an eye on your email for updates. Also, I recommend enabling transaction alerts and updating your online banking password for extra security. Would you like me to guide you through setting that up? Customer: Yes, that would be helpful. Agent (David): Absolutely! I’ll send you step-by-step instructions via email. Also, I’ll follow up in 3 days to update you on the investigation status. Customer: That sounds great. Thank you for your help, David. Agent (David): My pleasure! Stay safe, and don’t hesitate to reach out if you need further assistance. Have a great day!',
    prompt: `Analyze the following BFSI customer-agent conversation and answer the questions:{conversation} 1) Did the agent handle sensitive financial information securely and confidentially? (Yes/No)  2) How clear and effective was the agent's communication? (Poor, Average, Good)  3) Did the agent provide appropriate solutions for fraud resolution? (Poor, Average, Good)  4) How well did the agent manage the call flow? (Poor, Average, Good)  5) How professional and empathetic was the agent's demeanor? (Poor, Average, Good)  6) Did the agent offer to follow up on unresolved issues? (Yes/No). ${formatText}`,
  },
  {
    type: 'BFSI',
    text: 'Customer: Hi, I just noticed some unauthorized transactions on my credit card, and I need to report fraud. Agent (David): Hello! You’ve reached SecureBank Support. My name is David. How can I assist you? Customer: As I said, I found some unauthorized transactions and need to report fraud. Agent (David): Oh, okay. Let me check. First, I need to verify your identity. Can you confirm your last transaction and the last four digits of your card? Customer: Sure! My last valid transaction was $45 at Grocery Mart, and my card ends in 5678. Agent (David): Hmm… Give me a second… [Pauses for a while] Okay, I see three transactions flagged as suspicious: 1️⃣ $150 at TechZone 2️⃣ $200 at OnlineSportsGear.com 3️⃣ $50 at FastPay Wallet Transfer Do these look unfamiliar? Customer: No, I didn’t make any of those. Agent (David): Alright, I guess I have to start a fraud investigation for you. I’ve temporarily blocked your card for now. Customer: Oh, okay. What happens next? Agent (David): Umm... so basically, a dispute report will be filed, and we’ll investigate it. It usually takes around… 5 to 10 business days. You’ll probably get a refund if it’s fraudulent. Customer: Probably? So, I’m not guaranteed a refund? Agent (David): Well, usually, but I can’t promise anything until the investigation is done. Also, do you want a replacement card? I mean, you’ll need one if your card is blocked. Customer: Yes, please. Agent (David): Alright. You’ll get it in about 3-5 business days. Keep an eye on your email for tracking. Customer: Do I need to do anything else? Agent (David): Umm… maybe just check your emails, I guess. Oh, and you might want to change your online banking password. Customer: Could you guide me through that? Agent (David): Uh, I’ll send you some instructions via email. Just follow those. Customer: Okay… will you follow up on the fraud report? Agent (David): Oh yeah, sure… I can check back in a few days. You can also call us if you don’t hear back. Customer: Alright, thanks. Agent (David): Yeah, no problem. Have a good day.',
    prompt: `Analyze the following BFSI customer-agent conversation and answer the questions:{conversation} 1) Did the agent handle sensitive financial information securely and confidentially? (Yes/No)  2) How clear and effective was the agent's communication? (Poor, Average, Good)  3) Did the agent provide appropriate solutions for fraud resolution? (Poor, Average, Good)  4) How well did the agent manage the call flow? (Poor, Average, Good)  5) How professional and empathetic was the agent's demeanor? (Poor, Average, Good)  6) Did the agent offer to follow up on unresolved issues? (Yes/No). ${formatText}`,
  },
  {
    type: 'Education',
    text: 'Student: Hi, I recently enrolled in an online course, but I realized it’s not the right fit for me. I’d like to request a refund. Agent (Sarah): Hello! Thank you for reaching out to EduLearn Support. My name is Sarah, and I’d be happy to assist you. Could you please share your order ID or the email address used for enrollment? Student: Sure! My order ID is EDU123456 and my email is john.doe@email.com. Agent (Sarah): Thank you, John! I see that you enrolled in the Advanced Python Programming course last week. We do offer a 7-day refund policy, and since your request is within the time frame, I can process your refund. Student: That’s great! How long will it take to reflect in my account? Agent (Sarah): The refund will be processed to your original payment method within 5-7 business days. You’ll receive a confirmation email once it’s initiated. Student: Awesome. I was actually looking for a more beginner-friendly course. Do you have any recommendations? Agent (Sarah): Absolutely! If you’re looking for an introductory course, I’d recommend Python for Beginners or Introduction to Programming. Both are great for students who are just starting out. Would you like me to share the course details with you? Student: Yes, please! Also, do you offer any discounts? Agent (Sarah): Yes! We currently have a 20% discount on beginner-level courses for first-time students. If you enroll within the next 48 hours, you can use the code LEARN20 at checkout. Student: That sounds like a great deal! Can I use the refund amount directly to purchase the new course? Agent (Sarah): Good question! Instead of waiting for the refund, I can issue a direct credit to your EduLearn account, which you can use immediately to enroll in a new course. Would you like me to proceed with that option? Student: Yes, that would be perfect! Agent (Sarah): Done! The credit is now available in your account. You can enroll in the new course anytime using your EduLearn Wallet. I’ll also send you an email with course links and enrollment instructions. Student: Thank you so much! You’ve been really helpful. Agent (Sarah): My pleasure! If you need any more assistance, feel free to reach out. Happy learning! 📚',
    prompt: `Analyze the following education industry customer-agent conversation and answer the questions: {conversation} 1) Did the agent handle student information securely and confidentially? (Yes/No)   2) How clear and effective was the agent's communication? (Poor, Average, Good)   3) How well did the agent explain the refund process and alternative solutions? (Poor, Average, Good)   4) How effectively did the agent manage the call flow? (Poor, Average, Good)   5) How professional and helpful was the agent's demeanor? (Poor, Average, Good)   6) Did the agent offer relevant follow-ups or additional support? (Yes/No). ${formatText}`,
  },
  {
    type: 'Education',
    text: "Student: Hi, I recently enrolled in an online course, but I realized it’s not the right fit for me. I’d like to request a refund. Agent (Sarah): Hello! You’ve reached EduLearn Support. My name is Sarah. What’s your order ID or email? Student: Sure! My order ID is EDU123456 and my email is john.doe@email.com. Agent (Sarah): Okay, let me check… [Pause] Alright, I see that you enrolled in the Advanced Python Programming course. Student: Yes, but it’s too advanced for me. Can I get a refund? Agent (Sarah): Uh… I think we have a refund policy, let me check. [Pause] Oh, yeah, we do have a 7-day refund policy. Since your request is within the time frame, I can process it. Student: How long will it take to reflect in my account? Agent (Sarah): Umm… usually like a week? Maybe longer, depending on your bank. You’ll get an email when it’s done. Student: Alright. I was actually looking for a more beginner-friendly course. Do you have any recommendations? Agent (Sarah): Umm… yeah, we have some beginner courses. You can check them on our website. Student: Could you recommend one? Agent (Sarah): Well, there's Python for Beginners or something like that. I’d have to look it up. You might want to search for it yourself. Student: Do you offer any discounts? Agent (Sarah): Hmm… let me check. [Pause] Oh, yeah, we have a 20% discount on some courses, I think. I’m not sure if it applies to beginner courses, though. You’d have to try at checkout. Student: Can I use the refund amount directly to purchase the new course? Agent (Sarah): Uhh… good question. I think we do account credits, but I’m not sure. You might need to wait for the refund first. Student: Oh, okay. I was hoping to enroll immediately. Agent (Sarah): Yeah, I get that. You could email support to check if they can do anything faster. Student: Alright… thanks. Agent (Sarah): Yeah, no problem. Anything else? Student: No, that’s it. Agent (Sarah): Cool. Bye.",
    prompt: `Analyze the following education industry customer-agent conversation and answer the questions: {conversation} 1) Did the agent handle student information securely and confidentially? (Yes/No)   2) How clear and effective was the agent's communication? (Poor, Average, Good)   3) How well did the agent explain the refund process and alternative solutions? (Poor, Average, Good)   4) How effectively did the agent manage the call flow? (Poor, Average, Good)   5) How professional and helpful was the agent's demeanor? (Poor, Average, Good)   6) Did the agent offer relevant follow-ups or additional support? (Yes/No). ${formatText}`,
  },
  {
    type: 'Retail',
    text: 'Customer: Hi, I just received my order, but the item is damaged. I’d like to request a replacement or refund. Agent (Emma): Hello! Thank you for contacting ShopEase Customer Support. My name is Emma, and I’d be happy to assist you. Could you please share your order number or the email used for the purchase? Customer: Sure! My order number is RETAIL12345, and my email is jane.doe@email.com. Agent (Emma): Thanks, Jane! I see that you ordered a ceramic dinnerware set from our store. I’m really sorry that it arrived damaged. Could you describe the issue or share a picture of the damage? Customer: Yes, the dinner plates have cracks, and one is completely broken. I can send pictures if needed. Agent (Emma): That would be very helpful! You can upload the images through the support link I’m sending to your email. Once we verify the damage, we can proceed with a replacement or refund. Customer: Okay, I just uploaded the images. Agent (Emma): Got them! Since the damage is confirmed, you’re eligible for a free replacement or a full refund. Which option would you prefer? Customer: I’d like a replacement, please. Agent (Emma): Got it! I’ve placed a new order for your replacement, and it will be shipped within 24 hours. You’ll receive a tracking link once it’s dispatched. Customer: Do I need to return the damaged set? Agent (Emma): No, you don’t need to return it. You can dispose of it safely or donate any usable pieces. Customer: That’s great, thanks! What if the replacement also arrives damaged? Agent (Emma): In the rare case that happens, just contact us again, and we’ll make it right. Also, I’ve added a 10% discount to your account for your next purchase as a gesture of goodwill. Customer: Wow, that’s really nice! Thank you for the help. Agent (Emma): My pleasure! If you need any more assistance, feel free to reach out. Have a great day!',
    prompt: `Analyze the following retail industry customer-agent conversation and answer the questions: {conversation} 1) Did the agent handle customer information securely and confidentially? (Yes/No)   2) How clear and effective was the agent's communication? (Poor, Average, Good)   3) How well did the agent explain the return/replacement process? (Poor, Average, Good)   4) How effectively did the agent manage the call flow? (Poor, Average, Good)   5) How professional and empathetic was the agent's demeanor? (Poor, Average, Good)   6) Did the agent offer any follow-ups, discounts, or additional support? (Yes/No).  ${formatText}`,
  },
  {
    type: 'Retail',
    text: 'Customer: Hi, I just received my order, but the item is damaged. I’d like to request a replacement or refund. Agent (Emma): Hello. This is ShopEase Customer Support. What’s your order number or email? Customer: Sure! My order number is RETAIL12345, and my email is jane.doe@email.com. Agent (Emma): Alright, let me check... [Pause] Okay, you ordered a ceramic dinnerware set. Customer: Yes, and it arrived damaged. Agent (Emma): Oh. Um… Can you describe the issue? Customer: The dinner plates have cracks, and one is completely broken. I can send pictures if needed. Agent (Emma): Yeah, you’ll need to send pictures. I’ll email you a link. Customer: Okay, I just uploaded the images. Agent (Emma): Alright… [Pause] Let me check… [Pause] Okay, yeah, I see the damage. Customer: So what are my options? Agent (Emma): Umm… I guess we can offer a replacement or refund. Customer: I’d like a replacement, please. Agent (Emma): Hmm… okay. I’ll place a request. It should be shipped… soon. You’ll get a tracking link when it’s sent out. Customer: Do I need to return the damaged set? Agent (Emma): Uh… no, I don’t think so. You can just, like, throw it away or something. Customer: Alright… what if the replacement arrives damaged too? Agent (Emma): That’s… rare. But if it happens, just call us again. Customer: Okay. Agent (Emma): Anything else? Customer: No, that’s it. Agent (Emma): Cool. Bye.',
    prompt: `Analyze the following retail industry customer-agent conversation and answer the questions: {conversation} 1) Did the agent handle customer information securely and confidentially? (Yes/No)   2) How clear and effective was the agent's communication? (Poor, Average, Good)   3) How well did the agent explain the return/replacement process? (Poor, Average, Good)   4) How effectively did the agent manage the call flow? (Poor, Average, Good)   5) How professional and empathetic was the agent's demeanor? (Poor, Average, Good)   6) Did the agent offer any follow-ups, discounts, or additional support? (Yes/No). ${formatText}`,
  },
  {
    type: 'IT/ITES',
    text: 'Customer: Hi, I’m unable to access my cloud storage account. Every time I log in, it says authentication failed. Can you help me? Agent (Alex): Hello! Thank you for reaching out to TechCloud Support. My name is Alex, and I’d be happy to assist you. Can you please confirm your registered email ID? Customer: Sure! It’s mark.smith@email.com. Agent (Alex): Thanks, Mark! I see that your account is active, but there was a failed login attempt due to incorrect credentials. Have you tried resetting your password? Customer: Yes, but I didn’t receive the reset email. Agent (Alex): I understand the frustration. Let’s check—oh, I see that the reset email was sent but landed in your spam folder. Can you check there? Customer: Oh! I found it. Let me reset the password now. Agent (Alex): Great! I’ll wait while you do that. Customer: Done! But now I’m getting an error saying Multi-Factor Authentication (MFA) required. Agent (Alex): That’s expected. Since there were multiple login failures, your account requires MFA verification. Do you have access to the authenticator app or backup codes? Customer: No, I changed my phone recently, and I lost access to the authenticator app. Agent (Alex): No worries! I can help you disable MFA temporarily so you can log in and reconfigure it. For security reasons, I’ll need to verify your identity. Customer: Sure, what do you need? Agent (Alex): I’ve sent a one-time verification link to your registered email. Click it, and I’ll proceed with disabling MFA. Customer: Done! I’ve clicked the link. Agent (Alex): Perfect! I’ve now disabled MFA. You should be able to log in. Once inside, please re-enable MFA under security settings to keep your account protected. Customer: That worked! Thank you so much. Agent (Alex): You’re welcome! Also, I’ve sent a guide on MFA setup and a backup codes file for future logins. Let me know if you need any more help. Customer: That’s really helpful. Appreciate it! Agent (Alex): My pleasure! Have a great day!',
    prompt: `Analyze the following IT/ITES industry customer-agent conversation and answer the questions: {conversation} 1) Did the agent handle sensitive information securely and confidentially? (Yes/No)   2) How clear and effective was the agent's communication? (Poor, Average, Good)   3) How well did the agent explain the troubleshooting steps? (Poor, Average, Good)   4) How effectively did the agent manage the call flow? (Poor, Average, Good)   5) How professional and empathetic was the agent's demeanor? (Poor, Average, Good)   6) Did the agent offer proactive support or follow-ups? (Yes/No). ${formatText}`,
  },
  {
    type: 'IT/ITES',
    text: 'Customer: Hi, I’m unable to access my cloud storage account. Every time I log in, it says authentication failed. Can you help me? Agent (Alex): Uh… okay. What’s your email? Customer: It’s mark.smith@email.com. Agent (Alex): Alright, let me check… [Pause] Hmm. Your account is active. Looks like you entered the wrong password. Customer: But I already reset it, and I didn’t get the reset email. Agent (Alex): Well, it should’ve been sent. Did you check your spam? Customer: Oh! I found it. Let me reset it now. Agent (Alex): Cool. I’ll wait. Customer: Done! But now it says Multi-Factor Authentication (MFA) required. Agent (Alex): Yeah, that happens if you fail too many logins. Do you have your backup codes or authenticator app? Customer: No, I changed my phone recently and lost access. Agent (Alex): Oh… that’s a problem. Customer: So what do I do now? Agent (Alex): Uh… let me think. I *guess* I can disable MFA, but I need to verify your identity first. Customer: Sure, what do you need? Agent (Alex): I’ll send a link to your email. Click it. Customer: Done! Agent (Alex): Okay, I turned off MFA. You should be able to log in now. Customer: Finally! That worked. Agent (Alex): Yep. Customer: …So, should I re-enable MFA? Agent (Alex): If you want. Also, I think we have a guide somewhere. Hold on… [Pause] Never mind, just Google it. Customer: Uh… okay. Thanks? Agent (Alex): No problem. Later.',
    prompt: `Analyze the following IT/ITES industry customer-agent conversation and answer the questions: {conversation} 1) Did the agent handle sensitive information securely and confidentially? (Yes/No)   2) How clear and effective was the agent's communication? (Poor, Average, Good)   3) How well did the agent explain the troubleshooting steps? (Poor, Average, Good)   4) How effectively did the agent manage the call flow? (Poor, Average, Good)   5) How professional and empathetic was the agent's demeanor? (Poor, Average, Good)   6) Did the agent offer proactive support or follow-ups? (Yes/No). ${formatText}`,
  },
  {
    type: 'Public Sector',
    text: 'Citizen: Hi, I need some help with renewing my passport. My current one expires next month. Can you guide me through the process? Agent (Sarah): Hello! Thank you for reaching out to the National Passport Service Center. I’m Sarah, and I’d be happy to assist you. May I have your passport number to check your record? Citizen: Sure! It’s A12345678. Agent (Sarah): Thanks! I see that your passport is indeed expiring soon. Are you looking for a regular renewal or an expedited service? Citizen: What’s the difference? Agent (Sarah): A regular renewal takes about 4-6 weeks, while an expedited renewal takes 7-10 business days but comes with an additional processing fee. Citizen: I need my passport urgently for a business trip. Can I apply for the expedited one online? Agent (Sarah): Yes, you can! Just visit the official government portal and fill out the passport renewal application (Form DS-82). You’ll also need: ✔ A recent passport-size photo ✔ Your current passport ✔ A proof of travel document (like a flight ticket) ✔ Payment for the expedited processing fee Citizen: Got it. How do I submit the documents? Agent (Sarah): You can either mail them to the National Passport Processing Center or schedule an in-person appointment at the nearest passport office. Since your travel is urgent, I recommend booking an appointment. Citizen: Okay, I’ll go with the appointment. How do I book one? Agent (Sarah): You can book an appointment through our online scheduling system. Would you like me to send you the direct link to your email? Citizen: Yes, please. My email is j.doe@email.com. Agent (Sarah): Great! I’ve just sent the link. Please check your inbox. Once booked, carry all the required documents to your appointment. Citizen: Perfect! One more thing—can I track my application after submitting it? Agent (Sarah): Absolutely! You can track your passport status online using your application number or call our helpline for updates. Citizen: That’s really helpful. Thanks for the guidance! Agent (Sarah): My pleasure! If you have any more questions, feel free to call us back. Have a great day! ',
    prompt: ` Analyze the following public sector customer-agent conversation and answer the questions: {conversation} 1) Did the agent handle sensitive information securely and confidentially? (Yes/No)   2) How clear and effective was the agent's communication? (Poor, Average, Good)   3) How well did the agent explain the procedures? (Poor, Average, Good)   4) How effectively did the agent manage the conversation flow? (Poor, Average, Good)   5) How professional and courteous was the agent? (Poor, Average, Good)   6) Did the agent provide follow-up support or proactive assistance? (Yes/No).  ${formatText}`,
  },
  {
    type: 'Public Sector',
    text: 'Citizen: Hi, I need some help with renewing my passport. My current one expires next month. Can you guide me through the process? Agent (Sarah): Um… okay. What do you need help with? Citizen: Just the renewal process. What steps should I follow? Agent (Sarah): Uh, hold on… let me check. [Pause] You need to, like, fill out a form or something. Citizen: Okay, which form do I need? Agent (Sarah): Um, I think it’s DS-82? Yeah. You need that one. Citizen: Alright. Can I apply for expedited renewal online? I need my passport urgently. Agent (Sarah): Uh, yeah. I think so. But there’s a fee. Citizen: How much is the fee? Agent (Sarah): Not sure. You can check on the website. Citizen: …Right. So, where do I submit my documents? Agent (Sarah): You can mail them somewhere, or maybe go to an office. Citizen: Which office? Agent (Sarah): Um, let me see… [Pause] I don’t know, just check the website. Citizen: Can you at least send me the link to book an appointment? Agent (Sarah): Oh, yeah. What’s your email? Citizen: j.doe@email.com. Agent (Sarah): Alright, sending it now. You should get it soon. Citizen: Got it. One last thing—how do I track my application status? Agent (Sarah): I think you can check online or call someone. Not sure. Citizen: …Alright. Thanks, I guess. Agent (Sarah): Yeah, no problem. Bye.',
    prompt: `Analyze the following public sector customer-agent conversation and answer the questions: {conversation} 1) Did the agent handle sensitive information securely and confidentially? (Yes/No)   2) How clear and effective was the agent's communication? (Poor, Average, Good)   3) How well did the agent explain the procedures? (Poor, Average, Good)   4) How effectively did the agent manage the conversation flow? (Poor, Average, Good)   5) How professional and courteous was the agent? (Poor, Average, Good)   6) Did the agent provide follow-up support or proactive assistance? (Yes/No). ${formatText}`,
  },
];

const apiUrl = 'http://localhost:8081/api/analyze';

const runTests = async () => {
  let results = [];

  for (const testCase of testCases) {
    try {
      const response = await axios.post(apiUrl, testCase);
      results.push(response.data);
    } catch (error) {
      console.error('Error testing API:', error.response?.data || error.message);
      results.push({ error: 'Failed to analyze conversation' });
    }
  }

  console.log('Final Test Results:', JSON.stringify(results, null, 2));
};

runTests();
